# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'files/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_window(object):
    def setupUi(self, window):
        window.setObjectName("window")
        window.resize(850, 687)
        window.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.centralwidget = QtWidgets.QWidget(window)
        self.centralwidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.scrollArea.setMouseTracking(False)
        self.scrollArea.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 586, 600))
        self.scrollAreaWidgetContents.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        window.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(window)
        self.toolBar.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.toolBar.setMovable(False)
        self.toolBar.setAllowedAreas(QtCore.Qt.BottomToolBarArea|QtCore.Qt.TopToolBarArea)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName("toolBar")
        window.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.dockSearch = QtWidgets.QDockWidget(window)
        self.dockSearch.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockSearch.sizePolicy().hasHeightForWidth())
        self.dockSearch.setSizePolicy(sizePolicy)
        self.dockSearch.setMinimumSize(QtCore.QSize(245, 62))
        self.dockSearch.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.dockSearch.setFeatures(QtWidgets.QDockWidget.NoDockWidgetFeatures)
        self.dockSearch.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea)
        self.dockSearch.setWindowTitle("")
        self.dockSearch.setObjectName("dockSearch")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.dockWidgetContents_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.findBackButton = QtWidgets.QPushButton(self.dockWidgetContents_2)
        self.findBackButton.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.findBackButton.setObjectName("findBackButton")
        self.horizontalLayout.addWidget(self.findBackButton)
        self.findTextEdit = QtWidgets.QLineEdit(self.dockWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.findTextEdit.sizePolicy().hasHeightForWidth())
        self.findTextEdit.setSizePolicy(sizePolicy)
        self.findTextEdit.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.findTextEdit.setObjectName("findTextEdit")
        self.horizontalLayout.addWidget(self.findTextEdit)
        self.findNextButton = QtWidgets.QPushButton(self.dockWidgetContents_2)
        self.findNextButton.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.findNextButton.setObjectName("findNextButton")
        self.horizontalLayout.addWidget(self.findNextButton)
        self.dockSearch.setWidget(self.dockWidgetContents_2)
        window.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockSearch)
        self.dockWidget = QtWidgets.QDockWidget(window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget.sizePolicy().hasHeightForWidth())
        self.dockWidget.setSizePolicy(sizePolicy)
        self.dockWidget.setMinimumSize(QtCore.QSize(70, 97))
        self.dockWidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.dockWidget.setFeatures(QtWidgets.QDockWidget.NoDockWidgetFeatures)
        self.dockWidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dockWidget.setWindowTitle("")
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.treeView = QtWidgets.QTreeView(self.dockWidgetContents)
        self.treeView.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeView.sizePolicy().hasHeightForWidth())
        self.treeView.setSizePolicy(sizePolicy)
        self.treeView.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.treeView.setObjectName("treeView")
        self.treeView.header().setVisible(True)
        self.verticalLayout.addWidget(self.treeView)
        self.dockWidget.setWidget(self.dockWidgetContents)
        window.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.openFileAction = QtWidgets.QAction(window)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openFileAction.setIcon(icon)
        self.openFileAction.setObjectName("openFileAction")
        self.zoominAction = QtWidgets.QAction(window)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/zoomin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoominAction.setIcon(icon1)
        self.zoominAction.setObjectName("zoominAction")
        self.zoomoutAction = QtWidgets.QAction(window)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/zoomout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoomoutAction.setIcon(icon2)
        self.zoomoutAction.setObjectName("zoomoutAction")
        self.prevPageAction = QtWidgets.QAction(window)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/prev.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.prevPageAction.setIcon(icon3)
        self.prevPageAction.setObjectName("prevPageAction")
        self.nextPageAction = QtWidgets.QAction(window)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nextPageAction.setIcon(icon4)
        self.nextPageAction.setObjectName("nextPageAction")
        self.undoJumpAction = QtWidgets.QAction(window)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/undo-jump.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.undoJumpAction.setIcon(icon5)
        self.undoJumpAction.setObjectName("undoJumpAction")
        self.firstPageAction = QtWidgets.QAction(window)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/go-first.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.firstPageAction.setIcon(icon6)
        self.firstPageAction.setObjectName("firstPageAction")
        self.lastPageAction = QtWidgets.QAction(window)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/go-last.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.lastPageAction.setIcon(icon7)
        self.lastPageAction.setObjectName("lastPageAction")

        self.retranslateUi(window)
        QtCore.QMetaObject.connectSlotsByName(window)

    def retranslateUi(self, window):
        _translate = QtCore.QCoreApplication.translate
        window.setWindowTitle(_translate("window", "PdfTranslator"))
        self.toolBar.setWindowTitle(_translate("window", "toolBar"))
        self.findBackButton.setText(_translate("window", "Back"))
        self.findNextButton.setText(_translate("window", "Next"))
        self.openFileAction.setText(_translate("window", "Open"))
        self.openFileAction.setShortcut(_translate("window", "Ctrl+O"))
        self.zoominAction.setText(_translate("window", "Zoom In"))
        self.zoominAction.setShortcut(_translate("window", "Ctrl++"))
        self.zoomoutAction.setText(_translate("window", "Zoom Out"))
        self.zoomoutAction.setShortcut(_translate("window", "Ctrl+-"))
        self.prevPageAction.setText(_translate("window", "Prev Page"))
        self.prevPageAction.setShortcut(_translate("window", "Left"))
        self.nextPageAction.setText(_translate("window", "Next Page"))
        self.nextPageAction.setShortcut(_translate("window", "Right"))
        self.undoJumpAction.setText(_translate("window", "Jump Back"))
        self.undoJumpAction.setShortcut(_translate("window", "Shift+Backspace"))
        self.firstPageAction.setText(_translate("window", "First Page"))
        self.lastPageAction.setText(_translate("window", "Last Page"))
import resources_rc
